/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './app.vue',
    './error.vue',
  ],
  theme: {
    fontSize: {
      'sm': '12px',
      'normal': '14px',
      'md': '16px',
      'lg': '18px',
      'xl': '20px',
      '2xl': '24px',
      '4xl': '32px',
    },
    extend: {
      colors: {
        'primary-darker': '#030391',
        'primary-dark': '#030391BF',
        'primary-light': '#03039180',
        'primary-lighter': '#03039140',
        'secondary-darker': '#BFE1FF',
        'secondary-dark': '#BFE1FFBF',
        'secondary-light': '#BFE1FF80',
        'secondary-lighter': '#BFE1FF40',
        'tertiary-darker': '#275CF2',
        'tertiary-dark': '#275CF2BF',
        'tertiary-light': '#275CF280',
        'tertiary-lighter': '#275CF240',
        'gray-darker': '#0E0E2C',
        'gray-dark': '#0E0E2CBF',
        'gray-light': '#0E0E2C80',
        'gray-lighter': '#0E0E2C40',
        'danger-darker': '#ED4B9E',
        'danger-dark': '#ED4B9EBF',
        'danger-light': '#ED4B9E80',
        'danger-lighter': '#ED4B9E40',
        'safe-darker': '#00DC82',
        'safe-dark': '#00DC82BF',
        'safe-light': '#00DC8280',
        'safe-lighter': '#00DC8240',
        'slate-darker': '#0F172A',
        'slate-dark': '#64748B',
        'slate-light': '#F1F5F9',
        'slate-lighter': '#F8FaFC',
        'white': '#FFFFFF',
      },
      aspectRatio: {
        auto: 'auto',
        square: '1 / 1',
        video: '16 / 9'
      }
    },
  },
  plugins: [],
};
